- name: Update server
  dnf:
    name: "*"
    state: latest
  become: yes

- name: Reboot server
  reboot:

- name: Install epel-release
  dnf:
    name: epel-release
    state: present
  become: yes

- name: Install container-tools
  dnf:
    name: '@container-tools'
    state: present
  become: yes

- name: Install podman-compose
  pip:
    name: podman-compose
    executable: pip3
  become: yes

- name: Open firewall-ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 9090
    - 3000
    - 3100
  notify: reload firewalld
  become: yes

- name: Create monitoring user for podman
  user:
    name: mon
    shell: /bin/bash
    uid: 1010
  become: yes
