- name: Create directories
  file:
    path: /var/monitoring/loki-config
    state: directory
    owner: mon
    group: mon
  become: yes

- name: Copy loki-confg.yaml to new directory
  copy:
    src: loki-config.yaml
    dest: /var/monitoring/loki-config/loki-config.yaml
    owner: mon
    group: mon
  become: yes
